### ISSUE TITLE
Microsoft keyboards detection fixed in kernel 4.9

### ISSUE THREAD

**Issue by scaronni** [denilsonsa/udev-joystick-blacklist#20]
Hello,

Red Hat has contributed a few patches to the kernel:

https://bugzilla.redhat.com/show_bug.cgi?id=1325354#c13

But only one patch has been accepted upstream that fixes Microsoft keyboards:

https://git.kernel.org/cgit/linux/kernel/git/jikos/hid.git/commit/?h=for-next&id=1989dada7ce07848196991c9ebf25ff9c5f14d4e

It is included in kernel 4.9 and it is included as a backport to latest 4.8 updates on Fedora.
Would it be possible to have a separate branch with the Microsoft IDs removed? This way I can include only the required rules in the Fedora Steam package.

Thanks,
--Simone

**Comment by denilsonsa** [comment]
Instead of a different branch, I believe just saving the alternative files into a different directory will be enough (and simpler to manage).

Thank you! Sorry for the delay. Please keep us informed of new patches and fixes!
