### ISSUE TITLE
Wacom Intuos Pen (S) CTL-480 isn't in the blacklist

### ISSUE THREAD

**Issue by ChaloCanaria** [denilsonsa/udev-joystick-blacklist#32]
I found this as a solution for this issue I've had, but now I see the list of supported Wacom devices, I noticed my model isn't on it. I don't know too much about udev and actually nothing about GitHub, so I don't know how this works. So, uh... reporting this will make my Wacom tablet model to appear in the blacklist in a future update? Or is there a way to contribute by myself? I'm sorry if I look like a dummy right now. The device ID is 056a:030e
Screenshot that shows the issue. Using Linux Mint 18.1 KDE:
http://i.imgur.com/F56vN9G.png

**Comment by ChaloCanaria** [comment]
Ok, so I just made it by myself by looking for my tablet's IDs in the linuxwacom page. The lines I finally put in the device are:

SUBSYSTEM=="input", ATTRS{idVendor}=="056a", ATTRS{idProduct}=="030e", ENV{ID_INPUT_JOYSTICK}=="?*", ENV{ID_INPUT_JOYSTICK}=""
SUBSYSTEM=="input", ATTRS{idVendor}=="056a", ATTRS{idProduct}=="030e", KERNEL=="js[0-9]*", MODE="0000", ENV{ID_INPUT_JOYSTICK}=""

It isn't recognized as a gamepad by KDE, but it still isn't recognized as a tablet, either.

**Comment by denilsonsa** [comment]
Hello! I've added the device to the blacklist.

Regarding your questions…

I don't use KDE, I don't know if it has any UI for configuring a tablet. On the other hand, it should "just work", no configuration needed. Personally, [I've fine-tuned my device manually by running some commands](https://bitbucket.org/denilsonsa/small_scripts/src/default/xsetwacom_my_preferences.sh).

When will the rules be automatically updated in your system? I don't know. It depends on when the package gets updated in your distro. But you can also update the files manually.
