### ISSUE TITLE
Corsair Harpoon Gaming Mouse

### ISSUE THREAD

**Issue by Mar2ck** [denilsonsa/udev-joystick-blacklist#37]
The Corsair Harpoon mouse (CH-9301011 is my model) has this issue aswell

`Bus 001 Device 003: ID 1b1c:1b3c Corsair`

**Comment by denilsonsa** [comment]
Does it? I also have a Corsair Harpoon mouse and it works fine for me (no extra joystick devices). Maybe because I'm also using <https://github.com/ckb-next/ckb-next>.

I'm adding it to the blacklist anyway. Thanks!
