### ISSUE TITLE
added entry for my intuos3 tablet however it also breaks controller (steam pad)

### ISSUE THREAD

**Issue by teletrail** [denilsonsa/udev-joystick-blacklist#59]
hallo.

I added an entry for my wacom (intuos3 12x19) since it was not there and ran the rule generator script however though it did disable the entry for the wacom it also broke my steam controller.

any help would be appreciated.

**Comment by denilsonsa** [comment]
Hi!

You did not give enough information, so I can only help you based on some guesses.

I just added many more Wacom devices to the list (bb92e6ed29286bf554a46217366dc56f32b3a6d3).

I don't know how you downloaded/installed these udev rules… (Directly from GitHub? Through a package manager?) …but if you get an updated version of these rules, it should work.

Also, the Steam Controller is NOT part of these rules (ddb1c449285b2c470454729bb9b68f28dd0fde06), so if your controller stopped working, there is something else happening. If I were to guess, I'd guess that you either installed another set of rules specifically for the Steam Controller, or you installed this set of rules here from a fork that included the Steam Controller.

---

I'm closing this issue, assuming this will be enough to solve your problem. If that's not the case, feel free to reopen.
